### ISSUE TITLE
Axonix SDK for Android 4.3.0 crashes on Android 6 when it's trying to load and to show ads

### ISSUE THREAD

**Issue by neciogames** [AxonixRTB/axonix-android-sdk-releases#1]
# Axonix SDK for Android 4.3.0 crashes on Android 6 when it's trying to load and to show ads

**Steps to reproduce the error:**
1.) Download the SDK (axonix-android-sdk-releases-4.3.0)
2.) Add the demo project (AxonixDemo) to your workspace (e.g. at eclipse).
3.) Set up the new Google Play Services (Version: "8487000") on the demo project
4.) At the Manifest change the application ID value "insert-your-application-key" to a real one
5.) Build an "apk"
6.) Copy the "apk" to an Android 6 Device (please find the device details below)
7.) Install the "apk" on the test device
8.) Open the "apk"
9.) The "apk" will crash before a banner ad is shown or while loading an interstitial ad

**Axonix SDK Version:**
Axonix SDK for Android 4.3.0 released on 27 Nov 2014

**Google Play Service:**
Google Play Service Version: "8487000" (Google Play services 8.4 release December 2015)

**Device Details:**
Device: Galaxy S7 Edge (hero2lte)
Manufacturer: Samsung
Android-Version: Android 6.0.1
RAM (MB): 4096
Screen size: 1440 × 2560
Screen density (dpi): 640
OpenGL ES-Version: 3.1
Native Platform: armeabi-v7a
CPU-brand: Samsung
CPU-model: Exynos 8890

**Comment by osuka** [comment]
Thanks for reporting this, we will try to reproduce it and report back.

**Comment by neciogames** [comment]
Hey osuka,
how are you?
Have you been able to reproduce it? And do you have already an idea how to fix it?

**Comment by megaz** [comment]
Apologies for the delay in getting back to you, we tried to reproduce the issue but have not been able to do so (using a Samsung Galaxy S7 running Exynos 8890).  Have you got a log of the error so we can analyse the stack trace?  We're in the process of migrating our SDK to Android Studio (recommended IDE) so hopefully should make things easier when working with the Demo Project

**Comment by neciogames** [comment]
Seems that the Galaxy S6 has the same issue.
Samsung Galaxy S6 (zeroflte)
Android-Version Android 4.4 RAM (MB) 3072
Screen: 1440 × 2560 (dpi) 640
OpenGL ES-Version 3.1
Native Plattform armeabi-v7a
CPU Samsung
CPU-Model Exynos 7420

I sent all I got already mid of march to your publisher support (
publisher.support@axonix.com)

**Comment by osuka** [comment]
We have finally identified the error and pushed a new patch release (with a new JAR file, `axonix-android-sdk-4.4.0.jar`) that should fix all issues (it was due to a deprecated method in the webview classes). Thanks for reporting this!

https://github.com/AxonixRTB/axonix-android-sdk-releases/releases/tag/4.4.0

**Comment by TheLuckyCoder** [comment]
@megaz are you going to migrate to Android Studio?
